#!/bin/sh
set -e

host=$(hostname -i)
discovery_host=discovery

# Get the ip address of the discovery service, so it can be passed to the
# swarm slave container
discovery_ip=$(getent hosts $discovery_host| awk '{ print $1 }' | head -1)
if [ -z "$discovery_ip" ]; then
    >&2 echo "discovery host not found."
    exit 1
fi

export DOCKER_HOST=tcp://localhost:$DOCKER_PORT
timeout -t 30 /wait_on_daemon

# Start swarm slave
docker run \
    --add-host $discovery_host:$discovery_ip \
    --env SWARM_DISCOVERY \
    swarm:$SWARM_VERSION join \
    --addr=$host:$DOCKER_PORT
