#!/bin/sh

set -ex

host=$(hostname -i)
discovery_host=discovery

# Get the ip address of the discovery service, so it can be passed to the
# swarm slave container
discovery_ip=$(getent hosts $discovery_host| awk '{ print $1 }' | head -1)

# TODO: poll instead of sleep
sleep 2

# Start swarm slave
DOCKER_HOST=tcp://localhost:$DOCKER_PORT docker run \
    --add-host $discovery_host:$discovery_ip \
    --env SWARM_DISCOVERY \
    swarm:$SWARM_VERSION join \
    --addr=$host:$DOCKER_PORT
