#!/bin/sh
set -ex

# TODO: can this be removed with networks?
host=$(hostname -i | awk '{print $1}')

timeout -t 30 /wait_on_discovery

/dind docker daemon \
    -H 0.0.0.0:$DOCKER_PORT \
    --cluster-store ${SWARM_DISCOVERY}networks \
    --cluster-advertise $host:$DOCKER_PORT \
    $DOCKER_ARGS
