#!/bin/sh
set -e

host=$(hostname -i)
discovery_host=discovery

# Get the ip address of the discovery service, so it can be passed to the
# swarm slave container
discovery_ip=$(getent hosts $discovery_host| awk '{ print $1 }' | head -1)
if [ -z "$discovery_ip" ]; then
    >&2 echo "discovery host not found."
    exit 1
fi

timeout -t 30 /wait_on_daemon

# Start mesos slave
set -x
docker run \
    --add-host $discovery_host:$discovery_ip \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e MESOS_HOSTNAME=$host \
    -e MESOS_CONTAINERIZERS=docker \
    dnephin/docker-mesos:$MESOS_VERSION \
    slave --master=zk://discovery:2181/mesos \
          --docker_mesos_image=dnephin/docker-mesos:$MESOS_VERSION
